name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: kali
            context: ./kali
            image: hersoncruz/hackinglab-kali
            platform: linux/arm64/v8
          - name: metasploit
            context: ./metasploit
            image: hersoncruz/hackinglab-metasploit
            platform: linux/arm64/v8
          - name: nmap
            context: ./nmap
            image: hersoncruz/hackinglab-nmap
            platform: linux/arm64/v8
          - name: wireshark
            context: ./wireshark
            image: hersoncruz/hackinglab-wireshark
            platform: linux/arm64/v8
          - name: zap
            context: ./zap
            image: hersoncruz/hackinglab-zap
            platform: linux/arm64/v8
          - name: dvwa
            context: ./dvwa
            image: hersoncruz/hackinglab-dvwa
            platform: linux/arm64/v8
          - name: webgoat
            context: ./webgoat
            image: hersoncruz/hackinglab-webgoat
            platform: linux/arm64/v8
          - name: bwapp
            context: ./bwapp
            image: hersoncruz/hackinglab-bwapp
            platform: linux/amd64
          - name: vulnerable_api
            context: ./vulnerable_api
            image: hersoncruz/hackinglab-vulnerable_api
            platform: linux/arm64/v8
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.service.context }}
          platforms: ${{ matrix.service.platform }}
          push: true
          tags: |
            ${{ matrix.service.image }}:latest
            ${{ matrix.service.image }}:${{ github.sha }}
